    path(path, genpath('.'));

    %% Hard-coded constants.
    omega = 0.12;
    dims = [80 80 40];
    z_thickness = 10;
    z_center = dims(3)/2;
    eps_lo = 1.5;
    eps_hi = 13;



    %% Build up the base structure.

    mu = {ones(dims), ones(dims), ones(dims)};

    epsilon = {eps_lo*ones(dims), eps_lo*ones(dims), eps_lo*ones(dims)};

    my_shapes = {struct('type', 'rectangle', ...
                        'position', [0 0], ...
                        'size', [1e9 1e9], ...
                        'permittivity', eps_lo), ...
                struct('type', 'rectangle', ...
                        'position', [0 0], ...
                        'size', [1e9 12], ...
                        'permittivity', eps_hi)};

    epsilon = add_planar(epsilon, z_center, z_thickness, my_shapes); 

    [s_prim, s_dual] = stretched_coordinates(omega, dims, [10 10 0]);

    % Build the selection matrix, and reset values of epsilon.
    [S, epsilon] = planar_selection_matrix('alternate', epsilon, ...
                                            {[21 21], [41 41]}, eps_lo, ...
                                            z_center, z_thickness);


    %% Specify the parameterization of z
    z_param = struct('m', @(p) p, ...
                    'w', @(p) 0, ...
                    'p_range', ones(size(S,2), 1) * [0 1], ...
                    'scheme', 'discrete-diagonal');


    %% Specify modes

    % Allow for a simple way to specify a waveguide mode.
    wg = @(power, xpos, dir, mode_num) ...
                struct('type', 'wgmode', ...
                    'power', power, ...
                    'pos', {[xpos 1 1], [xpos dims(2) dims(3)]}, ...
                    'dir', dir, ...
                    'mode_num', mode_num);

    modes(1) = struct('omega', omega, ...
                    'in', wg(1, 15, 'x+', 1), ...
                    'out', [wg([0.9 1], 65, 'x', 1), ...
                            wg([0 0.1], 65, 'x', 2)], ...
                    's_prim', {s_prim}, ...
                    's_dual', {s_dual}, ...
                    'mu', {mu}, ...
                    'epsilon_const', {epsilon}, ...
                    'S', (eps_hi - eps_lo) * S);

    %% Construct the optimization problem
    opt_prob = make_opt_prob(z_param, modes)
