    %% Build up the base epsilon.
    omega = 0.12;
    dims = [80 80 1];
    z_thickness = 5;
    z_center = dims(3)/2;

    mu = {ones(dims), ones(dims), ones(dims)};

    wg = @(power, xpos, dir, mode_num) ...
                struct('type', 'wgmode', ...
                    'power', power, ...
                    'pos', {[xpos 1 1], [xpos dims(2) dims(3)]}, ...
                    'dir', dir, ...
                    'mode_num', mode_num);

    [s_prim, s_dual] = stretched_coordinates(omega, dims, [10 10 0]);

    epsilon = {1.5*ones(dims), 1.5*ones(dims), 1.5*ones(dims)};

    my_shapes = {struct('type', 'rectangle', ...
                        'position', [0 0], ...
                        'size', [1e9 1e9], ...
                        'permittivity', 1.5), ...
                struct('type', 'rectangle', ...
                        'position', [0 0], ...
                        'size', [1e9 12], ...
                        'permittivity', 13)};

    epsilon = add_planar(epsilon, z_center, z_thickness, my_shapes); 

    [S, epsilon] = planar_selection_matrix('serrated', epsilon, ...
                                            {[21 21], [60 60]}, ...
                                            z_center, z_thickness);


    %% Specify modes
    mode(1) = struct('omega', omega, ...
                    'in', wg(1, 15, 'x+', 1), ...
                    'out', wg([0.9 1], 65, 'x', 1), ...
                    's_prim', s_prim, ...
                    's_dual', s_dual, ...
                    'mu', mu, ...
                    'epsilon_const', epsilon, ...
                    'S', S);




    %% Specify z
    l = 10;
    z_spec = struct('m', @(p) p, ...
                    'w', @(p) 0, ...
                    'p_range', [0 1], ...
                    'scheme', 'discrete-diagonal');

    z_spec
    


